DATA_DIR = "/home/mooncyli/BU-RISE/"

CENTER_LOSS_WEIGHT = 10
ORIENTATION_LOSS_WEIGHT = 2.0
CE_LOSS_WEIGHT = 1.0

CENTER_CORRECT_RANGE = 10 #in px

HEIGHT = 120 #px
WIDTH = 160 #px
CAMERA_PARAMS = (
    615.0, # fx
    615.0, # fy
    WIDTH/2, # cx
    HEIGHT/2 # cy
)
TAG_SIZE = 0.15 #tag size in meters
TEST_SIZE = 50

POSE_WEIGHT = 2.0
X_CLASSES = 8
Y_CLASSES = 8
ANGLE_CLASSES = 72
TOTAL_CLASSES = X_CLASSES*Y_CLASSES*ANGLE_CLASSES
DIMENSIONS = '8x8x72'